<?php
/*
foreach($articles AS $article) {
    echo $user->getDescription()." - ".$user->getCreated()->format('d.m.Y')."\n";
    echo "    Reported by: ".$user->getReporter()->name."\n";
    echo "    Assigned to: ".$user->getEngineer()->name."\n";
    foreach($user->getProducts() AS $product) {
        echo "    Platform: ".$product->name."\n";
    }
    echo "\n";
}
*/
$title = 'My comments';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
<!-- <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'comment', 'action'=>'add')); /*NOtice without true no param is send*/?>">Add new translation</a> -->
    <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'article', 'action'=>'index'), false);?>">&lt; Back to the articles | </a>
    <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'comment', 'action'=>'add'), true);?>">Add New Comment</a>
</p>
<?php 
if($comments)
{
echo '<table class="table">';
echo '<tr>';
echo '<th>Title</th>';
echo '    <th>Text</th>';
echo '    <th>Author</th>';
echo '    <th>Language</th>';
echo '	<th>Created</th>';
echo '    <th>&nbsp;</th>';
echo '</tr>';
}
else
{
	echo $this->translate('There are no comments');
}
?>
<?php foreach ($comments as $comment) : ?>
<tr>
    <td><?php echo $this->escapeHtml($comment->getTitle());?></td>
    <td><?php echo $this->escapeHtml($comment->getText());?></td>
    <td><?php if (is_object($comment->getAuthor())) echo $this->escapeHtml($comment->getAuthor()->getUsername());?></td>
    <td><?php if (is_object($comment->getLanguage())) echo $this->escapeHtml($comment->getLanguage()->getName());?></td>
    <td><?php if (is_object($comment->getCreated())) echo $this->escapeHtml($comment->getCreated()->format('Y-m-d H:i:s'));?></td><!-- Notice: getArtcCreated() returns an object convert to string -->
    <td>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'comment', 'action'=>'edit', 'id2' => $comment->getId()), true);?>">Edit</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment>
            array('controller' => 'comment', 'action'=>'delete', 'id2' => $comment->getId()), true);?>" onclick="return confirm('Do you really want to delete the record?')">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>