<?php
$title = 'Latest articles';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php
if(!$articles)
{
    echo '<p>There no articles</p>';
}
else
{
    echo '<ul>';
    foreach ($articles as $article) :
?>
        <hr>
        <li>
            <h3>
                <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
                                    array('controller' => 'article', 'action'=>'view', 'id' => $article->getId()));?>">
                <?php echo $this->escapeHtml($article->getTitle());?>
                </a>
            </h3>
                <span><?php echo $article->getCreated()->format('F j, Y H:i'); if(is_object($article->getAuthor())) echo ' by ' . $this->escapeHtml($article->getAuthor()->getUsername());?></span>
            <?php echo $article->getIntroText();?>
        </li>
<?php
    endforeach;
    echo '</ul>';
}?>
<?php 
if($mostCommentedArticles)
{
echo '<b>Most commented articles</b>';
echo '<table class="table">';
echo '<tr>';
echo '	  <th>Title</th>';
echo '    <th>Intro Text</th>';
echo '    <th>Author</th>';
echo '    <th>Language</th>';
echo '	  <th>Created</th>';
echo '	  <th>Comments</th>';
echo '    <th>&nbsp;</th>';
echo '</tr>';
}
else
{
	echo 'There no articles';
}
?>

<?php $counter = 0;
foreach ($mostCommentedArticles as $article) : ?>
<tr>
    <td><a href="<?php 
		echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
                                    array('controller' => 'article', 'action'=>'view', 'id' => $article->getId()));?>">
									<?php echo $this->escapeHtml($article->getTitle());?></td>
    <td><?php echo $article->getIntrotext();?></td>
    <td><?php if (is_object($article->getAuthor())) echo $this->escapeHtml($article->getAuthor()->getUsername());?></td>
    <td><?php if (is_object($article->getLanguage())) echo $this->escapeHtml($article->getLanguage()->getName());?></td>
    <td><?php echo $this->escapeHtml($article->getCreated()->format('Y-m-d H:i:s'));?></td><!-- Notice: getCreated() returns an object convert to string -->
	<td><?php echo $countOfComments[$counter]; ?> </td>
    <td>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'translation', 'action'=>'index', 'id' => $article->getId()));?>">Translations</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'comment', 'action'=>'index', 'id' => $article->getId()));?>">Comments</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'article', 'action'=>'view', 'id' => $article->getId()));?>">View</a>
		<a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'article', 'action'=>'edit', 'id' => $article->getId()));?>">Edit</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment>
            array('controller' => 'article', 'action'=>'delete', 'id' => $article->getId()));?>" onclick="return confirm('Do you really want to delete this record?')">Delete</a>
    </td>
</tr>
<?php $counter++; endforeach; ?>
</table>

