<?php
$title = 'My articles';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'index', 'action'=>'add'));?>">Add new article</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Intro Text</th>
    <th>Author</th>
    <th>Language</th>
	<th>Parent</th>
	<th>Created</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($articles as $article) : ?>
<tr>
    <td><?php echo $this->escapeHtml($article->getTitle());?></td>
    <td><?php echo $this->escapeHtml($article->getIntrotext());?></td>
    <td><?php if (is_object($article->getAuthor())) echo $this->escapeHtml($article->getAuthor()->getUsername());?></td>
    <td><?php if (is_object($article->getLanguage())) echo $this->escapeHtml($article->getLanguage()->getName());?></td>
    <td><?php if (is_object($article->getParent())) echo $this->escapeHtml($article->getParent()->getTitle());?></td>
    <td><?php echo $this->escapeHtml($article->getCreated()->format('Y-m-d H:i:s'));?></td><!-- Notice: getCreated() returns an object convert to string -->
    <td>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'translation', 'action'=>'index', 'id' => $article->getId()));?>">Translations</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'comment', 'action'=>'index', 'id' => $article->getId()));?>">Comments</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'index', 'action'=>'view', 'id' => $article->getId()));?>">View</a>
		<a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'index', 'action'=>'edit', 'id' => $article->getId()));?>">Edit</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment>
            array('controller' => 'index', 'action'=>'delete', 'id' => $article->getId()));?>" onclick="return confirm('Do you really want to delete this record?')">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>