<?php
$title = 'My Categories';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
<a href="<?php echo $this->url('csn-cms/default', array('controller' => 'article', 'action'=>'index'), false);?>">&lt; Back to the articles | </a>
    <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'category', 'action'=>'add'));?>">Add new category </a>
	
</p>
<?php
if($categories)
{
echo '<table class="table">';
echo '<tr>';
echo '<th>Name</th>';
echo '<th>&nbsp;</th>';
echo '</tr>';
}
else
{
	echo 'There no categories';
}

foreach ($categories as $category) { ?>
<tr>
    <td><?php echo $this->escapeHtml($category->getName());?></td>
    <td>
		<a href="<?php echo $this->url('csn-cms/default',
            array('controller' => 'category', 'action'=>'view', 'id' => $category->getId()));?>">View articles</a>
		<a href="<?php echo $this->url('csn-cms/default', 
            array('controller' => 'category', 'action'=>'edit', 'id' => $category->getId()));?>">Edit</a>
        <a href="<?php echo $this->url('csn-cms/default', 
            array('controller' => 'category', 'action'=>'delete', 'id' => $category->getId()));?>" onclick="return confirm('Do you really want to delete this record?')">Delete</a>
    </td>
</tr>
<?php } ?>
</table>