<?php
$title = 'My Categories';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'category', 'action'=>'add'));?>">Add new category</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>&nbsp;</th>
</tr>
<?php

foreach ($categories as $category) { ?>
<tr>
    <td><?php
  // echo $this->escapeHtml($category->name);?></td>
    <td>
		<a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'category', 'action'=>'edit', 'id' => $category->getId()));?>">Edit</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment>
            array('controller' => 'category', 'action'=>'delete', 'id' => $category->getId()));?>" onclick="return confirm('Do you really want to delete this record?')">Delete</a>
    </td>
</tr>
<?php } ?>
</table>