<?php
$title = 'My articles';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'article', 'action'=>'add'));?>">Add new article | </a>
    <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'category', 'action'=>'index'));?>">Article Categories</a>
</p>
<?php 
if($articles)
{
echo '<table class="table">';
echo '<tr>';
echo '<th>Title</th>';
echo '    <th>Intro Text</th>';
echo '    <th>Author</th>';
echo '    <th>Language</th>';
echo '	<th>Created</th>';
echo '	<th>Parent</th>';
echo '    <th>&nbsp;</th>';
echo '</tr>';
}
else
{
	echo 'There no articles';
}
?>

<?php foreach ($articles as $article) : ?>
<tr>
    <td><?php echo $this->escapeHtml($article->getTitle());?></td>
    <td><?php echo $this->escapeHtml($article->getIntrotext());?></td>
    <td><?php if (is_object($article->getAuthor())) echo $this->escapeHtml($article->getAuthor()->getUsername());?></td>
    <td><?php if (is_object($article->getLanguage())) echo $this->escapeHtml($article->getLanguage()->getName());?></td>
    <td><?php if (is_object($article->getParent())) echo $this->escapeHtml($article->getParent()->getTitle());?></td>
    <td><?php echo $this->escapeHtml($article->getCreated()->format('Y-m-d H:i:s'));?></td><!-- Notice: getCreated() returns an object convert to string -->
    <td>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'translation', 'action'=>'index', 'id' => $article->getId()));?>">Translations</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'comment', 'action'=>'index', 'id' => $article->getId()));?>">Comments</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'article', 'action'=>'view', 'id' => $article->getId()));?>">View</a>
		<a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'article', 'action'=>'edit', 'id' => $article->getId()));?>">Edit</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment>
            array('controller' => 'article', 'action'=>'delete', 'id' => $article->getId()));?>" onclick="return confirm('Do you really want to delete this record?')">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>