<?php
$title = 'My tranlsations';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
<!-- <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'translation', 'action'=>'add')); /*NOtice without true no param is send*/?>">Add new translation</a> -->
    <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'index', 'action'=>'index'), false);?>">&lt; Back to the articles | </a>
    <a href="<?php echo $this->url('csn-cms/default', array('controller' => 'translation', 'action'=>'add'), true);?>">Add new translation</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Intro Text</th>
    <th>Author</th>
    <th>Language</th>
	<th>Created</th>
    <th>&nbsp;</th>
</tr>
<?php $article = $article[0];?>
<?php $translations = $article->getChildren(); ?>
<?php foreach ($translations as $article) : ?>
<tr>
    <td><?php echo $this->escapeHtml($article->getTitle());?></td>
    <td><?php echo $this->escapeHtml($article->getIntrotext());?></td>
    <td><?php if (is_object($article->getAuthor())) echo $this->escapeHtml($article->getAuthor()->getUsername());?></td>
    <td><?php if (is_object($article->getLanguage())) echo $this->escapeHtml($article->getLanguage()->getName());?></td>
    <td><?php echo $this->escapeHtml($article->getCreated()->format('Y-m-d H:i:s'));?></td><!-- Notice: getCreated() returns an object convert to string -->
    <td>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'comment', 'action'=>'index', 'id' => $article->getId()));?>">Comments</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'translation', 'action'=>'view', 'id2' => $article->getId()), true);?>">View</a>
		<a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'translation', 'action'=>'edit', 'id2' => $article->getId()), true);?>">Edit</a>
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment>
            array('controller' => 'translation', 'action'=>'delete', 'id2' => $article->getId()), true);?>" onclick="return confirm('Do you really want to delete this translation?')">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>